extends:
  - metarhia
  - plugin:sonarjs/recommended
  - prettier
plugins:
  - sonarjs
globals:
  Atomics: true
  SharedArrayBuffer: true
  AbortController: true
  jest: true
parserOptions:
  sourceType: module

