extends:
  - metarhia
  - plugin:prettier/recommended
  - plugin:sonarjs/recommended
plugins:
  - sonarjs
globals:
  Atomics: true
  SharedArrayBuffer: true
  jest: true
parserOptions:
  sourceType: module

