const HANDSHAKE_MESSAGE = 'SYNCBOX HELLO';
const EXEC_END_TIMEOUT = 1000;
const RESPONSE_TIMEOUT = 5000;

const messageType = {
  HANDSHAKE: 0,
  GET_FILE: 1,
  MKDIR: 2,
  SUCCESS: 3,
  FAIL: 4,
  TRANSACTION: 5,
  UNLINK: 6,
  UNLINK_DIR: 7,
};

export { HANDSHAKE_MESSAGE, messageType, EXEC_END_TIMEOUT, RESPONSE_TIMEOUT };
