const PORT = 4000;
const HANDSHAKE_MESSAGE = 'SYNCBOX HELLO';
const SUCCESS_MESSAGE = 'SYNCBOX OK';

const messageType = {
  HANDSHAKE: 0,
  GET_FILE: 1,
  MKDIR: 2,
  SUCCESS: 3,
  FAIL: 4,
  TRANSACTION: 5,
  UNLINK: 6,
  UNLINK_DIR: 7,
};

export { PORT, HANDSHAKE_MESSAGE, SUCCESS_MESSAGE, messageType };
