name: CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run lint-test --if-present
      - run: npm run test --if-present

      - name: Save ssh private key to file
        run: echo "$SSH_PRIVATE_KEY" > key && chmod 600 key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run deploy script on deployment server
        run: ssh -i key "$SERVER_ADDRESS" "cd syncbox && ./deploy.sh"
        env:
          SERVER_ADDRESS: ${{ secrets.SERVER_ADDRESS }}
